move arm64 build test to a separate workflow

diff --git a/.github/workflows/docker-build-arm64.yml b/.github/workflows/docker-build-arm64.yml
--- a/.github/workflows/docker-build-arm64.yml
+++ b/.github/workflows/docker-build-arm64.yml
@@ -1,4 +1,4 @@
-name: Build NV-Ingest Runtime Image
+name: Build NV-Ingest Runtime Image (arm64)
 
 # Trigger for pull requests and pushing to main
 on:
@@ -21,6 +21,10 @@ jobs:
       - name: Get current date (yyyy.mm.dd)
         run: echo "CURRENT_DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
 
+      # Set up QEMU emulation for arm64
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+
       # Set up Docker Buildx, useful for building multi-platform images
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
@@ -30,14 +34,15 @@ jobs:
       # base image and not the one hosted in nvcr.io
       - name: Build Docker image
         run: |
-          docker build --target runtime --build-arg GIT_COMMIT=${GITHUB_SHA} --build-arg BASE_IMG=ubuntu --build-arg BASE_IMG_TAG=jammy-20250415.1 -t nv-ingest:latest .
+          docker buildx create --use
+          docker buildx build --platform linux/arm64 --load --target runtime --build-arg GIT_COMMIT=${GITHUB_SHA} --build-arg BASE_IMG=ubuntu --build-arg BASE_IMG_TAG=jammy-20250415.1 -t nv-ingest:latest .
 
-      - name: Run Pytest inside Docker container
+      - name: Run
         run: |
-          docker run -e INSTALL_AUDIO_EXTRACTION_DEPS=true nv-ingest:latest pytest -rs -m "not integration" --cov nv_ingest --cov nv_ingest_client --cov nv_ingest_api --cov-report term --cov-report xml:coverage.xml tests/service_tests client/client_tests api/api_tests
-
-      - name: Upload test report
-        uses: actions/upload-artifact@v4
-        with:
-          name: pytest-report
-          path: coverage.xml
+          output=$(docker run --platform=linux/arm64 --rm -it nv-ingest:latest uname -m)
+          if [[ "$output" == "aarch64" ]]; then
+            echo "aarch64"
+          else
+            echo "Build failed"
+            exit 1
+          fi
